import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { api } from "../api";
import Checkbox from "@mui/material/Checkbox";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";

export default function Departments() {
    const { user } = useAuth();
    const [departments, setDepartments] = useState([]);
    const [edited, setEdited] = useState([]); // track changed rows for colour change
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [newDepartment, setNewDepartment] = useState("");

    // Fetch departments
    async function fetchDepartments() {
        try {
            const res = await api.get("/config/departments");
            if (Array.isArray(res.data.departments)) {
                setDepartments(res.data.departments);
            } else {
                setDepartments([]);
                setError(res.data.message || "No departments found.");
            }
        } catch (err) {
            console.error("Failed to fetch departments:", err.message);
            setError("Could not load departments.");
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        fetchDepartments();
    }, []);


    // Keep track of field changes in array until Save
    function handleFieldChange(id, field, value) {
        setDepartments((prev) =>
            prev.map((dept) => (dept._id === id ? { ...dept, [field]: value } : dept))
        );
        setEdited((prev) => [...new Set([...prev, id])]); // mark row update as pending
    }

    async function handleSave() {
        try {
            const updates = departments.filter((d) => edited.includes(d._id));
            if (updates.length === 0) {
                alert("No changes to save.");
                return;
            }

            const res = await api.put("/config/departments", { updates });

            // Line by line response generated by back end
            const results = res.data.results || [];
            // Note any failed results
            const failedIds = results.filter(r => !r.success).map(r => r.id);

            // Update local state only for successful saves
            setEdited(prev => prev.filter(id => failedIds.includes(id)));

            if (failedIds.length > 0) {
                // Optional: mark failed rows visually or toast message
                alert(
                    `Some updates failed:\n` +
                    results
                        .filter(r => !r.success)
                        .map(r => `${r.id}: ${r.message}`)
                        .join("\n")
                );
            } else {
                alert("All changes saved successfully.");
                setEdited([]); // clear edited state
            }

            // Optional: re-fetch data to sync backend truth
            const refreshed = await api.get("/config/departments");
            setDepartments(refreshed.data.departments);

        } catch (error) {
            console.error("Save failed:", error.message);
            alert("Failed to save changes.");
        }
    }

    async function handleInsert() {
        try {
            if (newDepartment.trim().length < 3) {
                alert("New departments must have a minimum of 3 characters.");
                return;
            }
            const res = await api.post("/config/departments", { department: newDepartment.trim() });
            alert("Department added successfully.");
            setNewDepartment("");
            await fetchDepartments();
        } catch (error) {
            console.error("Insert failed:", error.message);
            alert("Failed to insert changes.");
        }
    }


    if (loading) return <p>Loading departments...</p>;
    if (error) return <p>{error}</p>;

    return (
        <div>
            <h2>Configuration</h2>
            <h3>Departments</h3>
            <p>Welcome, {user?.fullName || user?.username}</p>
            <div>


                <table>
                    <thead>
                        <tr>
                            <th>Department Name</th>
                            <th>ID (dev only)</th>
                            <th>Active</th>
                        </tr>
                    </thead>

                    <tbody>
                        {(departments ?? []).map((dept) => (
                            <tr
                                key={dept._id}
                                style={{
                                    backgroundColor: edited.includes(dept._id)
                                        ? "#f1e1c3ff"
                                        : "transparent",
                                }}
                            >
                                <td>
                                    <TextField
                                        variant="standard"
                                        value={dept.department}
                                        onChange={(e) =>
                                            handleFieldChange(dept._id, "department", e.target.value)
                                        }
                                        fullWidth
                                    />
                                </td>
                                <td>{dept._id}</td>
                                <td>
                                    <Checkbox
                                        checked={dept.isActive}
                                        onChange={(e) =>
                                            handleFieldChange(dept._id, "isActive", e.target.checked)
                                        }
                                    />
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                <Button
                    variant="contained"
                    onClick={handleSave}
                    disabled={edited.length === 0}
                    style={{ marginBottom: "10px" }}
                >
                    Save
                </Button>
            </div>
            <div>
                <h4>Add New</h4>
                <TextField id="input-new-department" helperText="Minimum three characters" label="Department Name" variant="standard" onChange={(e) => setNewDepartment(e.target.value)} />
                <Button
                    variant="contained"
                    onClick={handleInsert}
                    disabled={newDepartment.length < 3}
                    style={{ marginBottom: "10px" }}
                >
                    Insert
                </Button>
            </div>
        </div>
    );
}
