export const MINIMUM_DEPARTMENT_LENGTH = 3;
export const MINIMUM_LOCATION_LENGTH = 3;
export const MINIMUM_CATEGORY_LENGTH = 3;
export const MINIMUM_USERNAME_LENGTH = 3;
export const MINIMUM_PASSWORD_LENGTH = 8;
export const MINIMUM_SYSTEM_LENGTH = 3;
export const MINIMUM_SYSTEM_CATEGORY_LENGTH = 3;
